### ISSUE TITLE
Update dead link for app creation in docs

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-zoom#30]
**Describe the bug**
The current link, e.g., [Create an SDK App](https://marketplace.zoom.us/docs/guides/build/sdk-app), is now dead, and we should point to https://developers.zoom.us/docs/meeting-sdk/create/ instead

**Steampipe version (`steampipe -v`)**
v0.19.3

**Plugin version (`steampipe plugin list`)**
v0.5.1

**To reproduce**
N/A

**Expected behavior**
The links should be valid

**Additional context**

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-plugin-zoom/pull/35
